---
- name: Install MSSQL Server and Command-Line Tools
  hosts: uadmin
  become: true
  tasks:
    - name: Add Microsoft repository key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main"
        state: present

    - name: Install MSSQL Server
      apt:
        name: mssql-server
        state: present

    - name: Install MSSQL command-line tools
      apt:
        name: mssql-tools
        state: present
