---
- name: Install Nginx
  hosts: sudo123
  remote_user: root
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: start Nginx
      service:
        name: nginx
        state: stoped
