---
- name: Install Apache Tomcat
  hosts: admin1
  gather_facts: no
  become: yes

  tasks:
    - name: Transfer Apache Tomcat package
      ansible.builtin.copy:
        src: /home/ubuntu/packages/apache-tomcat-10.0.19.tar.gz
        dest: /opt/apache-tomcat.tar.gz

    - name: Extract Apache Tomcat package
      ansible.builtin.unarchive:
        src: /opt/apache-tomcat.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/apache-tomcat  # Skip extraction if directory already exists

    # Additional tasks to configure Tomcat (e.g., set environment variables, create systemd service)
